apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: habesha-ingress
  namespace: habesha-table
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
    - host: habesha-table.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
  tls:
    - hosts:
        - habesha-table.example.com
      secretName: habesha-tls
